"""initial schema

Revision ID: 6d3d257eda35
Revises: 
Create Date: 2026-08-22 11:48:42.082037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d3d257eda35'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('db_type', sa.Enum('POSTGRES', 'MYSQL', 'SQLITE', name='dbtype', native_enum=False, length=20), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('database', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password_encrypted', sa.Text(), nullable=True),
    sa.Column('sqlite_path', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('UNTESTED', 'OK', 'FAILED', name='connectionstatus', native_enum=False, length=20), server_default='untested', nullable=False),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('saved_queries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sql_text', sa.Text(), nullable=False),
    sa.Column('table_hint', sa.String(length=255), nullable=True),
    sa.Column('chart_type', sa.Enum('LINE', 'BAR', 'PIE', 'NUMBER', 'TABLE', name='charttype', native_enum=False, length=20), server_default='table', nullable=False),
    sa.Column('x_field', sa.String(length=255), nullable=True),
    sa.Column('y_field', sa.String(length=255), nullable=True),
    sa.Column('series_field', sa.String(length=255), nullable=True),
    sa.Column('row_limit', sa.Integer(), server_default='1000', nullable=False),
    sa.Column('poll_interval_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'name', name='uq_saved_queries_conn_name')
    )
    with op.batch_alter_table('saved_queries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_queries_connection_id'), ['connection_id'], unique=False)

    op.create_table('query_execution_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('query_id', sa.String(length=36), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['query_id'], ['saved_queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('query_execution_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_query_execution_logs_executed_at'), ['executed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_query_execution_logs_query_id'), ['query_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('query_execution_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_query_execution_logs_query_id'))
        batch_op.drop_index(batch_op.f('ix_query_execution_logs_executed_at'))

    op.drop_table('query_execution_logs')
    with op.batch_alter_table('saved_queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_queries_connection_id'))

    op.drop_table('saved_queries')
    op.drop_table('connections')
    # ### end Alembic commands ###
