#!/usr/bin/env bash
# Run the whole production deploy on this machine, end to end, before it goes
# near EC2.
#
#     ./rehearse.sh            build, start, verify
#     ./rehearse.sh --clean    tear it down and delete the rehearsal state
#
# What this proves, and what it does not:
#
#   PROVES   the compose file composes, both images build, the analyzer
#            migrates a real Postgres over verify-full TLS, Caddy terminates
#            TLS and compresses, the dashboard proxies to the engine, sign-in
#            works end to end, the engine is unreachable from outside the
#            network, and preflight.sh / deploy.sh / verify.sh all run.
#
#   DOES NOT the RDS endpoint itself, the VPC security groups, or the EC2
#            security group. Those exist only in AWS, and verify.sh run ON the
#            instance is what checks them.
#
# Everything it creates lives in deploy/.rehearsal/ and in a compose project
# named `switchboard-rehearsal`, so it cannot collide with a real deployment on
# the same host.

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Exported BEFORE lib.sh is sourced, so the values it reads at source time are
# the rehearsal ones. Setting them afterwards is what broke the first run of
# this script: the overlay was ignored, no postgres container was created, and
# the analyzer came up pointed at nothing.
export SWITCHBOARD_ENV_FILE="$HERE/.rehearsal/env"
export SWITCHBOARD_COMPOSE_EXTRA="$HERE/docker-compose.rehearsal.yml"
export COMPOSE_PROJECT_NAME=switchboard-rehearsal

source "$HERE/lib.sh"

REHEARSAL_DIR="$DEPLOY_DIR/.rehearsal"
CERTS="$REHEARSAL_DIR/certs"
mkdir -p "$REHEARSAL_DIR"

if [[ "${1:-}" == "--clean" ]]; then
	section "Tearing down"
	compose down -v --remove-orphans 2>/dev/null || true
	rm -rf "$REHEARSAL_DIR"
	pass "rehearsal containers, volumes and state removed"
	exit 0
fi

printf '%sSwitchboard rehearsal%s  %s\n' "$C_BOLD" "$C_RESET" "$(date -u +%FT%TZ)"

# --- 1. a certificate authority and a server certificate --------------------

section "Rehearsal TLS material"

mkdir -p "$CERTS"
if [[ -f "$CERTS/server.key" && -f "$CERTS/ca.crt" ]]; then
	pass "certificates already present"
else
	# A CA, and a server certificate signed by it for the name `postgres` -
	# which is the hostname the analyzer resolves on the compose network, and
	# therefore the name sslmode=verify-full checks. Getting this right is the
	# point: a rehearsal that used `require` would exercise none of it.
	openssl req -x509 -newkey rsa:2048 -days 365 -nodes \
		-keyout "$CERTS/ca.key" -out "$CERTS/ca.crt" \
		-subj "/CN=Switchboard Rehearsal CA" >/dev/null 2>&1

	openssl req -newkey rsa:2048 -nodes \
		-keyout "$CERTS/server.key" -out "$CERTS/server.csr" \
		-subj "/CN=postgres" >/dev/null 2>&1

	# subjectAltName, not just the CN: every modern TLS client ignores the
	# common name entirely, and a certificate without a matching SAN fails
	# verify-full with an error that points at the CN it just ignored.
	openssl x509 -req -in "$CERTS/server.csr" -days 365 \
		-CA "$CERTS/ca.crt" -CAkey "$CERTS/ca.key" -CAcreateserial \
		-out "$CERTS/server.crt" \
		-extfile <(printf 'subjectAltName=DNS:postgres,DNS:localhost\n') >/dev/null 2>&1

	rm -f "$CERTS/server.csr" "$CERTS/ca.srl"
	chmod 644 "$CERTS/ca.crt" "$CERTS/server.crt"
	chmod 644 "$CERTS/server.key"   # copied to 600 inside the container
	pass "generated a CA and a server certificate for CN=postgres (SAN: postgres, localhost)"
fi

# --- 2. rehearsal configuration ---------------------------------------------

section "Rehearsal configuration"

if [[ ! -f "$ENV_FILE" ]]; then
	cat > "$ENV_FILE" <<EOF
# Generated by rehearse.sh. Local throwaway - not a production configuration.
SWITCHBOARD_PUBLIC_HOST=localhost
SWITCHBOARD_HTTP_PORT=8080
SWITCHBOARD_HTTPS_PORT=8443
DATABASE_URL=postgresql://switchboard:rehearsal-only-not-a-real-password@postgres:5432/switchboard?sslmode=verify-full&sslrootcert=/app/certs/trust-bundle.pem
FAE_FERNET_KEY=$(openssl rand -base64 32 | tr '+/' '-_')
WEB_CONCURRENCY=1
FAE_LOG_LEVEL=INFO
FAE_SCHEDULER_ENABLED=false
FAE_AUTO_MIGRATE=true
DASHBOARD_CONTEXT=../../fraud-analyzer-dashboard
EOF
	chmod 600 "$ENV_FILE"
	pass "wrote $ENV_FILE (mode 600)"
else
	pass "reusing $ENV_FILE"
fi
info "the DSN uses sslmode=verify-full against the CA above, exactly as production does"

# --- 3. build and start -----------------------------------------------------

section "Build and start"
info "first run builds two images; the dashboard's Next build is the slow half"

compose build
pass "images built"

compose up -d --remove-orphans
pass "stack started"

# --- 4. wait -----------------------------------------------------------------

section "Waiting for health"

for svc in analyzer dashboard; do
	deadline=$((SECONDS + 180)); state=unknown
	while [[ $SECONDS -lt $deadline ]]; do
		cid="$(compose ps -q "$svc" 2>/dev/null || true)"
		[[ -n "$cid" ]] && state="$(docker inspect -f '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' "$cid" 2>/dev/null || echo unknown)"
		[[ "$state" == "healthy" ]] && break
		[[ "$state" == "exited" || "$state" == "dead" ]] && break
		sleep 3
	done
	if [[ "$state" == "healthy" ]]; then
		pass "$svc is healthy"
	else
		fail "$svc is $state" "Log follows:"
		compose logs --tail 40 "$svc" | sed 's/^/        /'
	fi
done

if [[ $FAILURES -gt 0 ]]; then
	summary "Rehearsal" || true
	die "The stack did not come up. Nothing was verified."
fi

# --- 5. an administrator, so the sign-in check has something to sign in as ---

section "Seed account"

# example.com, not a .test address: the engine validates the email before it
# looks up an account, and a non-deliverable domain is refused at 422 without
# authentication ever running. A sign-in check against such an address tests
# the validator, not the sign-in.
REHEARSAL_EMAIL="rehearsal@example.com"
REHEARSAL_PASSWORD="Rehearsal-$(openssl rand -hex 8)!"

# `fae` is the installed entrypoint (pyproject [project.scripts]); there is no
# `python -m app.cli`. The password is a typer prompt with confirmation, so it
# is fed twice on stdin rather than passed as a flag - an argument would be
# visible in `ps` to every user on the box.
if printf '%s\n%s\n' "$REHEARSAL_PASSWORD" "$REHEARSAL_PASSWORD" \
	| compose exec -T analyzer fae create-admin \
		--email "$REHEARSAL_EMAIL" --name "Rehearsal Admin" --no-claim >/dev/null 2>&1; then
	pass "created $REHEARSAL_EMAIL"
else
	# Either it already exists from an earlier run, or the flags differ. Not
	# fatal: verify.sh's own checks do not need an account, and the sign-in
	# check below reports honestly if it cannot run.
	warn "could not create the rehearsal administrator" \
		"Probably already exists from a previous run. Sign-in check may be skipped."
fi

# --- 6. the real thing: run the production scripts --------------------------

section "Running preflight.sh"
"$DEPLOY_DIR/preflight.sh" || warn "preflight reported failures" \
	"Some are expected in rehearsal: this is not EC2, and localhost is not a public DNS name."

section "Running verify.sh"
printf '\n'
if printf '%s\n' "$REHEARSAL_PASSWORD" | "$DEPLOY_DIR/verify.sh" --login "$REHEARSAL_EMAIL"; then
	VERIFY_RESULT=0
else
	VERIFY_RESULT=1
fi

printf '\n'
if [[ $VERIFY_RESULT -eq 0 ]]; then
	cat <<EOF
$(printf '%s' "$C_GREEN$C_BOLD")Rehearsal passed.$(printf '%s' "$C_RESET")

  The stack is running locally at https://localhost:8443/
  Sign in as $REHEARSAL_EMAIL

  The same scripts now run on EC2 unchanged. Tear this down first:
      ./rehearse.sh --clean
EOF
else
	cat <<EOF
$(printf '%s' "$C_RED$C_BOLD")Rehearsal found failures.$(printf '%s' "$C_RESET")

  Fix them here, where it costs nothing, rather than on the instance.
      docker compose --env-file $ENV_FILE -f docker-compose.prod.yml -f docker-compose.rehearsal.yml logs analyzer
EOF
fi
exit $VERIFY_RESULT
